# Default values for sqlpad.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image: sqlpad/sqlpad:2.8.0
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
ingress:
  enabled: true
  hosts:
    - sqlpad.gosu.ai
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  tls:
    - secretName: sqlpad
      hosts:
        - sqlpad.gosu.ai
google_client_id: "1013908672460-a8a17l9dpi32r94q65ob7f259od8at13.apps.googleusercontent.com"
google_client_secret: "Fr2tac_xfIxp2oYQ6o8nuiuq"
public_url: "https://sqlpad.gosu.ai"
whitelisted_domains: "gosu.ai"
admin_email: "nb@gosu.ai"
